apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: https://github.com/hschoi1104/argocd-cluster-bootstrap.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true